name: cato
run-name: ${{ github.actor }}  Cato setup
on: [push]
jobs:
  cato:
    runs-on: ubuntu-latest
    steps:
      - run: pip install python3
      - run: python3 cota.py FILE-NAME-HERE
      - run: echo "Checking if job done"
      - name: Job done successfully
        uses: actions/checkout@v3

