name: cobrella
run-name: ${{ github.actor }}  Cobrella setup
on: [push]
jobs:
  cato:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting up!"
      - run: cd cato
      - run: python3 cobrella.py test.py
      - run: echo "Checking if job done"
      - name: Job done successfully
        uses: actions/checkout@v3
